#define CT_VERTEX_SEMANTIC_POSITION 0
#define CT_VERTEX_SEMANTIC_NORMAL0 1
#define CT_VERTEX_SEMANTIC_NORMAL1 2
#define CT_VERTEX_SEMANTIC_TANGENT0 3
#define CT_VERTEX_SEMANTIC_TANGENT1 4
#define CT_VERTEX_SEMANTIC_SKININDICES0 5
#define CT_VERTEX_SEMANTIC_SKININDICES1 6
#define CT_VERTEX_SEMANTIC_SKINBONES0 7
#define CT_VERTEX_SEMANTIC_SKINBONES1 8
#define CT_VERTEX_SEMANTIC_TEXTCOORD0 9
#define CT_VERTEX_SEMANTIC_TEXTCOORD1 10
#define CT_VERTEX_SEMANTIC_TEXTCOORD2 11
#define CT_VERTEX_SEMANTIC_TEXTCOORD3 12
#define CT_VERTEX_SEMANTIC_COLOR0 13
#define CT_VERTEX_SEMANTIC_COLOR1 14
#define CT_VERTEX_SEMANTIC_MAX 16

struct ct_vertex_loader_ctx {
    uint instance_id;
    uint active_channels;
    uint num_vertices;
    uint num_sets;

    vec4 offset[CT_VERTEX_SEMANTIC_MAX / 4];
    vec4 stride[CT_VERTEX_SEMANTIC_MAX / 4];
    vec4 buffer_idx[CT_VERTEX_SEMANTIC_MAX / 4];

    //  vec3 position;
};
