name: "XCompile Build & Test"

on:
  pull_request:
  push:
    #branches: ["main"]
    paths:
      - "bin/**"
      - "src/**"
      - "include/**"
      - "externals/**"
      - "build.zig"

concurrency:
  group: ${{ github.head_ref || github.run_id }}-${{ github.actor }}
  cancel-in-progress: true

jobs:
  build:
    name: Cross-compile build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      # - name: Prepare
      #   run: sudo apt-get update && sudo apt-get install libgtk-3-dev

      # - name: Build x86_64-linux Debug
      #   run: .ci/build.sh x86_64-linux x86_64-linux-gnu Debug
      - name: Build x86_64-macos Debug
        run: .ci/build.sh x86_64-linux x86_64-macos Debug
      - name: Build x86_64-windows Debug
        run: .ci/build.sh x86_64-linux x86_64-windows Debug

      - name: x86_64-linux Debug
        uses: actions/cache@v3
        with:
          path: build/Debug/x86_64-linux/
          key: x86_64-linux-Debug-cache-${{ github.sha }}
      - name: x86_64-macos Debug
        uses: actions/cache@v3
        with:
          path: build/Debug/x86_64-macos/
          key: x86_64-macos-Debug-cache-${{ github.sha }}
      - name: x86_64-windows Debug
        uses: actions/cache@v3
        with:
          path: build/Debug/x86_64-windows/
          key: x86_64-windows-Debug-cache-${{ github.sha }}

  test-x86_64-macos:
    name: Test x86_64-macos Debug
    runs-on: macos-13
    timeout-minutes: 2
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .ci/x86_64-macos-test.sh
            fixtures/
      - name: Download build
        uses: actions/cache@v3
        with:
          path: build/Debug/x86_64-macos/
          key: x86_64-macos-Debug-cache-${{ github.sha }}
          fail-on-cache-miss: true
      - name: Test
        run: sh .ci/x86_64-macos-test.sh Debug

  #  TODO: i dont know why but i see files, persmision looks ok
  #        but cant run because file not found... WTF
  # test-x86_64-linux:
  #   name: Test x86_64-linux Debug
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 2
  #   needs: build
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4
  #       with:
  #         sparse-checkout: |
  #           .ci/x86_64-macos-linux.sh
  #           fixtures/
  #     - name: Download build
  #       uses: actions/cache@v3
  #       with:
  #         path: build/Debug/x86_64-linux/
  #         key: x86_64-linux-Debug-cache-${{ github.sha }}
  #         fail-on-cache-miss: true
  #         enableCrossOsArchive: true
  #     - name: Test
  #       run: sh .ci/x86_64-linux-test.sh Debug

  test-x86_64-windows:
    name: Test x86_64-windows Debug
    runs-on: windows-latest
    timeout-minutes: 2
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .ci/x86_64-windows-test.ps1
            fixtures/
      - name: Download build
        uses: actions/cache@v3
        with:
          path: build/Debug/x86_64-windows/
          key: x86_64-windows-Debug-cache-${{ github.sha }}
          fail-on-cache-miss: true
          enableCrossOsArchive: true
      - name: configure Pagefile
        uses: al-cheb/configure-pagefile-action@v1.4
        with:
          minimum-size: 8GB
          maximum-size: 16GB
          disk-root: "C:"
      - name: Test
        run: .ci/x86_64-windows-test.ps1 Debug

  # docs:
  #   name: Publish docs
  #   needs: [test-x86_64-linux, test-x86_64-macos, test-x86_64-windows]
  #   uses: ./.github/workflows/docs.yaml

  cleanup:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    if: ${{ always() }}
    needs:
      # - test-x86_64-linux
      - test-x86_64-macos
      - test-x86_64-windows
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Cleanup
        run: |
          gh extension install actions/gh-actions-cache

          REPO=${{ github.repository }}

          ## Setting this to not fail the workflow while deleting cache keys. 
          set +e
          echo "Deleting caches..."

          gh actions-cache delete x86_64-linux-Debug-cache-${{ github.sha }} -R $REPO --confirm
          gh actions-cache delete x86_64-macos-Debug-cache-${{ github.sha }} -R $REPO  --confirm
          gh actions-cache delete x86_64-windows-Debug-cache-${{ github.sha }} -R $REPO --confirm

          echo "Done"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
